name = "telegram-proxy"
main = "src/index.js"
compatibility_date = "2024-11-01"
workers_dev = true

[[kv_namespaces]]
binding = "INVITES"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_NAMESPACE_ID"

[triggers]
crons = ["* * * * *"]

[vars]
PUBLIC_BASE_URL = "http://94.182.92.79/meeting"
BOT_USERNAME = "Meetingir_mir_bot"

[observability]
enabled = false
