server {
    listen 80;
    server_name 94-182-92-79.sslip.io;

    location = /meeting {
        return 301 /meeting/;
    }

    location /meeting/ {
        alias /var/www/date-invite/;
        index index.html;
        try_files $uri $uri/ /meeting/index.html;
    }
}
